# 使用语言
language: node_js
## node版本
node_js: stable
# 设置监听哪个分支
branches:
  only:
    - master
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
  - npm install -g hexo-cli
install:
  # 不用yarn的话这里改成 npm i 即可
  - npm install
script:
  - hexo clean
  - hexo generate
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git config user.name "ninglee"
  - git config user.email "ning531267557@gmail.com"
  - git add --all
  - git commit -m "version 1"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

notifications:
  email: false

env:
  global:
    - GH_REF=github.com/gutouyu/blog.git
